development:
  adapter: mysql2
  database: feminadb_dev
  username: feminadb_dev
  password: feminadb_dev
  host: 127.0.0.1
  encoding: utf8mb4

test:
  adapter: mysql2
  database: feminadb_test
  username: feminadb_test
  password: feminadb_test
  host: localhost
  encoding: utf8mb4
  flags: 65536 # CLIENT_MULTI_STATEMENTS, so we can do all TRUNCATE in one command

production:
  adapter: mysql2
  database: feminadb
  username: feminadb
  password: feminadb
  host: 127.0.0.1 # "localhost" makes the driver look for a socket in the wrong place. By default.
  encoding: utf8mb4
