# Messenger: how we use Google Talk to send messages from FeminaDB
messenger:
  jid: feminadb@feminahip.or.tz/FeminaDB
  password: BugDovPiNig3
  host: talk.google.com

  # Note: These recipients must have authorized the sender.
  # To do this, log in to mail.google.com as the client specified in
  # config/messenger.yml, then make sure you have used "Invite to Chat" for
  # each recipient.

  # Users who are to get a message when a new Special Order is created.
  # special_order_created_recipients:
  #   - adamh@feminahip.or.tz
  #   - zakaria@feminahip.or.tz
  special_order_created_recipients:

  # Users who are to get a message when a Special Order is approved.
  # Note: the person who filed the Special Order will always be messaged,
  # also.
  special_order_approved_recipients:

  # Users who are to get a message when a Special Order is denied.
  # Note: the person who filed the Special Order will always be messaged,
  # also.
  special_order_denied_recipients:
