development:
  secret_key_base: "4fc1c93d2be05c2a7ad7f3641132282c38955ffa3904e33164bcd403107afc2e1ef23f74f1fc4055a259a8cc8461f98c8526bb71d8671d0144f20afec844017b"
  oauth_client_id: "669704988220-s0asacgosskdq6i5ipf5h2g73u8c4lgo.apps.googleusercontent.com"
  oauth_client_secret: "AL_5981mnc1oVsB4AgG_7CCr"
  telerivet_api_key: "Q2trKPFk336ZavHjvkaPES1Qjso0LGPj" # Revoke API access when not testing
  telerivet_project_id: "c9e22351"

test:
  secret_key_base: "4fc1c93d2be05c2a7ad7f3641132282c38955ffa3904e33164bcd403107afc2e1ef23f74f1fc4055a259a8cc8461f98c8526bb71d8671d0144f20afec844017b"
  oauth_client_id: "669704988220-s0asacgosskdq6i5ipf5h2g73u8c4lgo.apps.googleusercontent.com"
  oauth_client_secret: "AL_5981mnc1oVsB4AgG_7CCr"
  telerivet_api_key: "Q2trKPFk336ZavHjvkaPES1Qjso0LGPj" # Revoke API access when not testing
  telerivet_project_id: "c9e22351"

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  oauth_client_id: <%= ENV["OAUTH_CLIENT_ID"] %>
  oauth_client_secret: <%= ENV["OAUTH_CLIENT_SECRET"] %>
  telerivet_api_key: <%= ENV["TELERIVET_API_KEY"] %>
  telerivet_project_id: <%= ENV["TELERIVET_PROJECT_ID"] %>
