#!/usr/bin/env ruby

require_relative '../config/boot'
require_relative '../config/environment'

def sql(s)
  User.connection.execute(s)
end

#for table in %w(bulk_order_creators clubs customer_notes customer_types customers delivery_methods districts issue_box_sizes issue_notes issues orders publications regions roles roles_users standing_orders users waiting_orders)
#  sql("DELETE FROM #{table} WHERE deleted_at IS NOT NULL")
#  sql("ALTER TABLE #{table} DROP COLUMN deleted_at")
#end

sql("DELETE FROM standing_orders WHERE customer_id NOT IN (SELECT id FROM customers)")
sql("DELETE FROM waiting_orders WHERE customer_id NOT IN (SELECT id FROM customers)")
sql("DELETE FROM issues WHERE publication_id NOT IN (SELECT id FROM publications)")
sql("DELETE FROM orders WHERE issue_id NOT IN (SELECT id FROM issues)")
sql("DELETE FROM orders WHERE customer_id NOT IN (SELECT id FROM customers)")
sql("UPDATE orders SET standing_order_id = NULL WHERE standing_order_id NOT IN (SELECT id FROM standing_orders)")

#sql("ALTER TABLE delivery_methods DROP COLUMN warehouse_id")
#sql("DROP TABLE warehouses")
