#!/usr/bin/env ruby

require_relative '../config/boot'
require_relative '../config/environment'

def sql(s)
  User.connection.execute(s)
end

#for table in %w(bulk_order_creators clubs customer_notes customer_types customers delivery_methods districts issue_box_sizes issue_notes issues orders publications regions roles roles_users standing_orders users waiting_orders)
#  sql("DELETE FROM #{table} WHERE deleted_at IS NOT NULL")
#  sql("ALTER TABLE #{table} DROP COLUMN deleted_at")
#end
#
#sql("DELETE FROM standing_orders WHERE customer_id NOT IN (SELECT id FROM customers)")
#sql("DELETE FROM waiting_orders WHERE customer_id NOT IN (SELECT id FROM customers)")
#sql("DELETE FROM issues WHERE publication_id NOT IN (SELECT id FROM publications)")
#sql("DELETE FROM orders WHERE issue_id NOT IN (SELECT id FROM issues)")
#sql("DELETE FROM orders WHERE customer_id NOT IN (SELECT id FROM customers)")
#sql("UPDATE orders SET standing_order_id = NULL WHERE standing_order_id NOT IN (SELECT id FROM standing_orders)")
#
#sql("ALTER TABLE delivery_methods DROP COLUMN warehouse_id")
#sql("DROP TABLE warehouses")
#
#sql("ALTER TABLE customers ADD COLUMN delivery_address VARCHAR(512) NOT NULL")
#sql("UPDATE customers SET delivery_address = CONCAT_WS(', ', CONCAT('via ', CASE deliver_via WHEN '' THEN NULL ELSE deliver_via END), CASE address WHEN '' THEN NULL ELSE address END, CASE route WHEN '' THEN NULL ELSE route END, CONCAT('p.o. box ', CASE po_box WHEN '' THEN NULL ELSE po_box END))")
#sql("ALTER TABLE customers DROP COLUMN deliver_via, DROP COLUMN route, DROP COLUMN po_box, DROP COLUMN address")
#
#sql("ALTER TABLE orders ADD COLUMN region VARCHAR(255) NOT NULL") # dunno why MySQL allows NOT NULL here, but let's go with it
#sql("UPDATE orders SET region = (SELECT name FROM regions WHERE id = orders.region_id)")
#sql("ALTER TABLE orders DROP COLUMN region_id")
#sql("ALTER TABLE orders ADD COLUMN delivery_method VARCHAR(255) NOT NULL") # NOT NULL, weird, yup
#sql("UPDATE orders SET delivery_method = (SELECT name FROM delivery_methods WHERE id = orders.delivery_method_id)")
#sql("ALTER TABLE orders DROP COLUMN delivery_method_id")
#sql("UPDATE orders SET contact_details = CONCAT_WS(': ', contact_name, contact_details)")
#sql("ALTER TABLE orders DROP COLUMN contact_name")
#sql("ALTER TABLE orders CHANGE deliver_via delivery_address VARCHAR(512) NOT NULL")
#sql("ALTER TABLE publications DROP COLUMN packing_hints")
#sql("ALTER TABLE issues DROP COLUMN packing_hints")
#sql("ALTER TABLE issues DROP COLUMN quantity")
#sql("ALTER TABLE issues DROP COLUMN price")
#
#sql("DROP TABLE delayed_jobs")
#sql("DROP TABLE versions")
